version: 0.0
os: linux
files:
  - source: /   # 모든 파일을 소스 디렉토리에서 가져옴
    destination: /home/ubuntu/action/auruda-gate  # auruda-gate 디렉토리로 복사
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu/action/auruda-gate
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755  # 디렉토리와 파일 권한 설정

hooks:
  ApplicationStart:
    - location: auruda-gate/scripts/deploy.sh  # 상대 경로로 수정
      timeout: 100
      runas: ubuntu
